# Generated by Django 3.2.3 on 2021-12-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='otpuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('tokn', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'gestion serveur',
                'ordering': ['id'],
            },
        ),
    ]
