# Generated by Django 3.2.3 on 2021-12-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cryptoapp', '0002_alter_otpuser_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpuser',
            old_name='tokn',
            new_name='token',
        ),
    ]
