# Generated by Django 3.2.3 on 2021-12-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cryptoapp', '0003_rename_tokn_otpuser_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='otpuser',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
